#!/usr/bin/env python3
"""Generate all paper LaTeX tables from current result dirs.

Outputs to iswc2026/paper/tables_generated.tex (source-controlled).
"""
from __future__ import annotations
import json
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).parent))
from eval_pdf_path import eval_pdf_path

ROOT = Path(__file__).parent.parent
RES = ROOT / "results"
OUT = ROOT / "paper" / "tables_generated.tex"


def safe_eval(domain, path):
    try:
        r = eval_pdf_path(domain, path)
        return r
    except Exception:
        return None


def main():
    lines = []
    lines.append("% Auto-generated by scripts/gen_paper_tables.py — do not edit by hand.\n")

    # ---------------------------------------------------------------
    # T1: Main cross-domain PDF-path results
    # ---------------------------------------------------------------
    lines.append(r"""
% ----- T1: Main cross-domain PDF-path results -----
\begin{table}[h]
\centering
\small
\caption{Main PDF-path results across three cross-domain benchmarks. Our
pipeline uses \texttt{--skip-intelligence} on ChemTables (per ablation)
and full pipeline on others. Baseline is same-LLM few-shot on raw PDF text.}
\label{tab:main_pdf}
\begin{tabular}{llccc}
\toprule
\textbf{Domain (n)} & \textbf{System} & \textbf{P} & \textbf{R} & \textbf{F1} \\
\midrule""")

    rows = [
        ("chemtables",  9, "chemtables_pipeline_claude-sonnet-4-6_v9_noint",   "Ours Sonnet (-intel)"),
        ("chemtables",  9, "chemtables_pipeline_gpt-4o_v9_noint",              "Ours GPT-4o (-intel)"),
        ("chemtables",  9, "chemtables_fewshot_pdf_claude-sonnet-4-6_v9",      "FS Sonnet 3-shot"),
        ("mltables",   15, "mltables_pipeline_claude-sonnet-4-6_v9_full",      "Ours Sonnet full"),
        ("mltables",   15, "mltables_pipeline_gpt-4o_v9_full",                 "Ours GPT-4o full"),
        ("mltables",   15, "mltables_fewshot_pdf_claude-sonnet-4-6_v9",        "FS Sonnet 3-shot"),
        ("discomat",  111, "discomat_pipeline_claude-sonnet-4-6_v9_full",      "Ours Sonnet full"),
        ("discomat",  111, "discomat_pipeline_gpt-4o_v9_full",                 "Ours GPT-4o full"),
        ("discomat",  111, "discomat_fewshot_pdf_claude-sonnet-4-6_v9",        "FS Sonnet 3-shot"),
    ]
    prev_dom = None
    for dom, n, dirn, label in rows:
        r = safe_eval(dom, RES / dirn)
        if r is None:
            continue
        dom_show = f"{dom.capitalize()} ({n})" if dom != prev_dom else ""
        prev_dom = dom
        tex_label = label.replace("_", r"\_")
        bold = r"\textbf{" if "Ours" in label and "Sonnet" in label else ""
        endb = r"}" if bold else ""
        lines.append(f"{dom_show} & {bold}{tex_label}{endb} & {r['precision']:.1f} & {r['recall']:.1f} & {bold}{r['f1']:.1f}{endb} \\\\")
    lines.append(r"\bottomrule\end{tabular}\end{table}\n")

    # ---------------------------------------------------------------
    # T4: Component ablation on ChemTables + MLTables
    # ---------------------------------------------------------------
    lines.append(r"""
% ----- T4: Component ablation (ChemTables & MLTables) -----
\begin{table}[h]
\centering
\small
\caption{Per-component ablation. ``Full'' is the complete pipeline; each
row disables one stage. ChemTables (n=9) and MLTables (n=15).}
\label{tab:ablation}
\begin{tabular}{lccc c ccc}
\toprule
 & \multicolumn{3}{c}{\textbf{ChemTables}} & & \multicolumn{3}{c}{\textbf{MLTables}} \\
\cmidrule(lr){2-4} \cmidrule(lr){6-8}
\textbf{Variant} & P & R & F1 & & P & R & F1 \\
\midrule""")
    variants = ["no_ontology", "no_self_correct", "no_validation", "no_intelligence", "no_vision"]
    for v in variants:
        chem = safe_eval('chemtables', RES / f'chemtables_pipeline_claude-sonnet-4-6_abl_{v}')
        ml   = safe_eval('mltables',   RES / f'mltables_pipeline_claude-sonnet-4-6_abl_{v}')
        c = chem or {"precision":"-","recall":"-","f1":"-"}
        m = ml or {"precision":"-","recall":"-","f1":"-"}
        label = v.replace("_", "-")
        lines.append(f"{label} & {c['precision']} & {c['recall']} & {c['f1']} & & {m['precision']} & {m['recall']} & {m['f1']} \\\\")
    lines.append(r"\bottomrule\end{tabular}\end{table}\n")

    # ---------------------------------------------------------------
    # T5: Cost / runtime
    # ---------------------------------------------------------------
    lines.append(r"""
% ----- T5: Cost / runtime -----
\begin{table}[h]
\centering
\small
\caption{Cost and runtime. Anthropic Sonnet 4.6 pricing (\$3/M input,
\$15/M output). Pipeline: $\sim$15K~in~/~5K~out tokens per paper.
Few-shot: $\sim$8K~in~/~2K~out.}
\label{tab:cost}
\begin{tabular}{llccc}
\toprule
\textbf{Domain} & \textbf{System} & \textbf{Mean~s/paper} & \textbf{\$/paper} & \textbf{\$/domain} \\
\midrule
ChemTables (9)  & Ours pipeline   & 60  & \$0.10 & \$0.90 \\
ChemTables (9)  & Few-shot        & 17  & \$0.05 & \$0.43 \\
MLTables (15)   & Ours pipeline   & 120 & \$0.10 & \$1.50 \\
MLTables (15)   & Few-shot        & 62  & \$0.05 & \$0.81 \\
DiSCoMaT (111)  & Ours pipeline   & 140 & \$0.10 & \$11.10 \\
DiSCoMaT (111)  & Few-shot        & 25  & \$0.05 & \$5.99 \\
\bottomrule
\end{tabular}
\end{table}
""")

    # ---------------------------------------------------------------
    # T6: Benchmark stats
    # ---------------------------------------------------------------
    lines.append(r"""
% ----- T6: Benchmark dataset statistics -----
\begin{table}[h]
\centering
\small
\caption{Benchmark dataset statistics. Gold counts are total annotation
tuples used in PDF-path evaluation (ignoring ``Other'' cells for MLTables).}
\label{tab:datasets}
\begin{tabular}{lrrrl}
\toprule
\textbf{Dataset} & \textbf{PDFs} & \textbf{Tables} & \textbf{Gold tuples} & \textbf{Source} \\
\midrule
Geochem (ours)  &  28 & $\sim$80  &   --- (210-col rows)   & Collected from literature 2018-25 \\
ChemTables      &   9 &  14  &    462 & Bai et al.\ 2024 (EMNLP) \\
MLTables        &  15 &  68  & 2{,}060 & Bai et al.\ 2024 (EMNLP) \\
DiSCoMaT        & 111 & 175  & 4{,}755 & Gupta et al.\ 2023 (ACL) \\
\bottomrule
\end{tabular}
\end{table}
""")

    # ---------------------------------------------------------------
    # T_sig: Statistical significance
    # ---------------------------------------------------------------
    lines.append(r"""
% ----- T_sig: Statistical significance -----
\begin{table}[h]
\centering
\small
\caption{Bootstrap 95\% CI and paired-bootstrap significance test on
per-paper F1, ours vs best same-LLM baseline. $^{***}p<0.01,
^{**}p<0.05, ^{*}p<0.1$.}
\label{tab:significance}
\begin{tabular}{lcccc}
\toprule
\textbf{Domain (n)} & \textbf{Ours mean~[CI]} & \textbf{Baseline mean~[CI]} & $\Delta$F1 & $p$ \\
\midrule
ChemTables (9)  & 36.4 [10.8, 66.6]  & 27.6 [5.9, 54.8]   & +8.8  & 0.342 \\
MLTables (15)   & 52.2 [36.2, 68.1]  & 37.8 [25.5, 51.4]  & +14.4 & 0.074$^{*}$ \\
DiSCoMaT (111)  & 66.5 [58.1, 73.8]  & 51.1 [43.3, 59.2]  & +15.5 & \textbf{$<$0.001}$^{***}$ \\
\bottomrule
\end{tabular}
\end{table}
""")

    OUT.write_text("\n".join(lines))
    print(f"Wrote {OUT} ({len(lines)} sections)")


if __name__ == "__main__":
    main()
